sudo: true
language: node_js
node_js:
  - "7"
  
before_install:
  - sudo apt-get update
  - sudo apt-get install autoconf
  - sudo apt-get install libtool
  - sudo apt-get install build-essential
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8